
;[env:esp32]
;platform = espressif32@3.3
;board = esp32dev

;[env:esp32-s3-devkitc-1-n16r8v]
;platform = espressif32
;board = esp32-s3-devkitc-1-n16r8v

[env:esp32_s3_MCN4]
platform = espressif32
board = esp32_s3_MCN4
;board_build.psram = true

framework = arduino
build_unflags = -fno-rtti
upload_port = COM6
monitor_port = COM6
board_build.f_cpu = 240000000L
monitor_speed = 115200
board_build.partitions = max_spiffs_4.csv

build_type = debug
monitor_filters = esp32_exception_decoder